workflows:
  android:
    name: Android Kotlin Build
    instance_type: mac_mini
    scripts:
      - echo "Running Gradle build"
      - ./gradlew clean build  # Run Gradle build command (adjust for your project as necessary)
      - ./gradlew test  # Run unit tests if you have them (adjust if using Android Test or other test types)
    artifacts:
      - app/build/outputs/apk/release/app-release.apk  # Path to the APK output after the build